Sovrin Call enabled
hyperledger/indy-test-automation pull request #120
Opened 2023-01-10 08:10 UTC by pSchlarb

Fixes `--payments` flag.
Addition of Sovrin callable GithubActions workflow.
Removal of duplicates.
Forced LF endings

2023-01-10 14:29 UTC, WadeBarnes requested changes
A few small items to review.  Also I don't think `prepare_client.sh` and prepare_node.sh` ever get used.  Should they be deleted?

2023-01-10 14:29 UTC, WadeBarnes commented on system/conftest.py
> +    # os.environ["HOME"] = "/home/user"
Can be removed

2023-01-10 14:29 UTC, WadeBarnes commented on system/requirements-ubuntu-2004.txt
> +# pytest-asyncio>=0.14.0
Remove the commented out lines

2023-01-10 14:29 UTC, WadeBarnes commented on system/requirements.txt
> +# pytest-asyncio>=0.14.0
Remove the commented out lines

2023-01-10 14:29 UTC, WadeBarnes commented on system/docker/run.sh
> +fi
This could be cleaned up.  The only difference here is the requirements file used for install.

2023-01-10 14:29 UTC, WadeBarnes commented on system/docker/prepare_client.sh
> +docker_routine_path="$repo_path/system_node_only/docker"
The system_node_only folder is being deleted by this PR.

2023-01-10 14:29 UTC, WadeBarnes commented on system/docker/prepare_node.sh
> +docker_routine_path="$repo_path/system_node_only/docker"
The `system_node_only` folder is being deleted by this PR.

2023-01-11 11:04 UTC, pSchlarb commented
I don't think they should be deleted, because they provide a handy way to create the images, when working locally and not in GHA.

2023-01-11 13:29 UTC, WadeBarnes commented
> I don't think they should be deleted, because they provide a handy way to create the images, when working locally and not in GHA.
The `prepare.sh` script is used for that.  It builds the client and node images.  `prepare_client.sh` and `prepare_node.sh`, in their current state do not match how the images are being built in the `prepare.sh` script.  If they are to be kept, they will need to be updated, which is extra development and testing effort to keep them synced with the processes in the `prepare.sh` script.  I'm recommending removing them for that reason.

2023-01-11 13:47 UTC, WadeBarnes requested changes
One small change needed to retain support for other ubuntu versions.  Even though support for 16.04 is being dropped now.

2023-01-11 15:36 UTC, WadeBarnes approved these changes

2023-01-11 15:36 UTC, merged